### ISSUE TITLE
Service Intent must be explicit

### ISSUE THREAD

**Issue by silent1** [onepf/OpenIAB#457] opened 2015-03-02 03:22 UTC
I was pulling in version 0.9.8.2 through gradle. Unfortunately, all I have is a short stacktrace, but here it is:

Error Message:
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.billing.InAppBillingService.BIND }

Short Stacktrace:
0	java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.billing.InAppBillingService.BIND }
1	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1691)
2	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1790)
3	at android.app.ContextImpl.bindService(ContextImpl.java:1768)
4	at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
5	at org.onepf.oms.appstore.GooglePlay.isBillingAvailable(GooglePlay.java:134)

**Comment by RomanZhilich** [comment] 2015-03-02 03:30
Looks like another duplicate of #415. There's definitely some issue with Lollopop, however I wasn't able to reproduce it on any of my Nexus devices even once...

**Comment by Lakedaemon** [comment] 2015-03-02 07:22
I just received a crash report with the same issue.
Happened on Android 5.0 on a Samsung SM-G900F (Galaxy S5) with library 0.9.8.6

looks to me like the whole public boolean isBillingAvailable(final String packageName) method
should be enclosed in a try catch finally block.

Also, given my crash reports, it looks like the same user was doing fine with previous versions of my software where I xas building against 0.9.8.3.1 and 0.9.8.4 (I just switched to 0.9.8.6) 


  java.lang.IllegalArgumentException
:Service Intent must be explicit
:Intent { act=com.android.vending.billing.InAppBillingService.BIND }
at  android.app.ContextImpl.validateServiceIntent (ContextImpl.java : 1982)
at  android.app.ContextImpl.bindServiceCommon (ContextImpl.java : 2090)
at  android.app.ContextImpl.bindService (ContextImpl.java : 2068)
at  android.content.ContextWrapper.bindService (ContextWrapper.java : 559)
at  org.onepf.oms.appstore.GooglePlay.isBillingAvailable (GooglePlay.java : 134)
at  org.onepf.oms.OpenIabHelper$12.run (OpenIabHelper.java : 847)
at  java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java : 1112)
at  java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java : 587)
at  java.lang.Thread.run (Thread.java : 818)

**Comment by Lakedaemon** [comment] 2015-03-02 07:31
I just looked at the ContextImpl.validateServiceIntent 

Look at this : on Android 5.0+, you have this :  

private void More ...validateServiceIntent(Intent service) {
1672        if (service.getComponent() == null && service.getPackage() == null) {
1673            if (getApplicationInfo().targetSdkVersion >= Build.VERSION_CODES.LOLLIPOP) {
1674                IllegalArgumentException ex = new IllegalArgumentException(
1675                        "Service Intent must be explicit: " + service);
1676                throw ex;
1677            } else {
1678                Log.w(TAG, "Implicit intents with startService are not safe: " + service
1679                        + " " + Debug.getCallers(2, 3));
1680            }
1681        }
1682    }

Is there any chance that service.getComponent() == null && service.getPackage() == null with your implementation ? on what code path ?

**Comment by Lakedaemon** [comment] 2015-03-02 07:37
it looks at android.app.ContextImpl.bindServiceCommon  isn't at line 2090 on stock ContextImpl code
Samsung (or the user) might be using it's own ContextImpl class

**Comment by RomanZhilich** [comment] 2015-03-02 12:05
If you look through the history of the bug I mentioned earlier, you'll see that I came to same conclusion. I'll try to workaround it the same way I did with Aamazon.

Closing this one as duplicate of #415.

**Closed by RomanZhilich** 2015-03-02 12:05 UTC
