### ISSUE TITLE
Black screen when click to buy

### ISSUE THREAD

**Issue by Anglinadev** [onepf/OpenIAB#441] opened 2015-01-25 19:43 UTC
Hey guys i followed your sample game and integrated it with my game but when i click to buy it goes to black screen and nothing comes.
I followed all steps and sample app is working fin but mine is not :(

this is the game
https://play.google.com/store/apps/details?id=com.Ibnesina.pkBhaag

**Comment by RomanZhilich** [comment] 2015-01-26 15:22
I'm afraid I'll need more information then that.

Please post here options you've used and log from your device.

**Comment by AntonGitName** [comment] 2015-01-28 17:57
Unfortunately, I cannot reproduce your problem. I have downloaded the game that you have specified. And this is what I get before and after pressing a coin on a screen:
![screenshot_2015-01-28-20-49-35](https://cloud.githubusercontent.com/assets/4163544/5943429/eb2f0eba-a72f-11e4-9236-0db292c8f10f.png)
![screenshot_2015-01-28-20-49-41](https://cloud.githubusercontent.com/assets/4163544/5943432/ef08fd98-a72f-11e4-982b-30af9ec3c921.png)
As you can see I don't have a black screen but a normal purchase dialog instead. So, please, specify your problem and steps how it can be reproduced&

**Comment by ajaybirla** [comment] 2015-01-29 19:24
Hello All,

@Anglinadev might be saying that why there is black screen behind the white purchase popup?

And i have the same question. Why there is a black screen behind purchase popup?
How i can remove it?

This is my game when i click on Remove Ads button.

![screenshot_2015-01-30-00-34-24](https://cloud.githubusercontent.com/assets/6366521/5964477/621f653e-a81a-11e4-8ccf-2d09a4b274e5.png)

And this is farmville when i clicked on Coins button.

![screenshot_2015-01-30-00-45-00](https://cloud.githubusercontent.com/assets/6366521/5964487/7b327b88-a81a-11e4-99fd-4e4ce7af4731.png)

See the difference? No black screen behind purchase popup.

How can i remove it?

**Comment by Anglinadev** [comment] 2015-01-31 13:13
Confused now.
its working on some mobiles, in my device is showing totally black screen but in my friend and your device is showing perfect..
is there any device problem?

**Comment by ajaybirla** [comment] 2015-01-31 13:24
@Anglinadev Share your screenshot.

**Comment by RomanZhilich** [comment] 2015-02-02 14:47
Well, to be honest I have no idea what causes this behavior. Maybe this can be fixed with some Theme attribute or manifes flag, but I didn't find anything.
All I can say is that [Google sample](https://developer.android.com/training/in-app-billing/preparing-iab-app.html#GetSample) shows black background too, so it's unlikely to have anything to do with our library.

**Comment by ajaybirla** [comment] 2015-02-02 14:58
Thanks @RomanZhilich @akarimova I found the solution and yes, you are right, by adding theme attribute into OpenIAB activity removes black background.

<activity android:name="org.onepf.openiab.UnityProxyActivity"
              android:launchMode="singleTask"
              android:label="@string/app_name"
              android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"
              android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      </activity>

**Comment by RomanZhilich** [comment] 2015-02-02 15:07
Well, thanks for posting the solution. Take care.

**Closed by RomanZhilich** 2015-02-02 15:07 UTC
